name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 'latest'
    - name: Configure
      run: cmake -Bbuild -H.
    - name: Build
      run: cmake --build build --config Release
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: ExportLabelsPlugin
        path: build/
